name: eddieantonio
markdown: kramdown

safe: true

# Some metadata... like my social media handles, etc.
me:
  github: https://github.com/eddieantonio
  website: eddieantonio.ca
  resume: /resume/
  cv: /cv/
  twitter: https://twitter.com/_eddieantonio
  blog: http://www.eddieantonio.ca/blog/
  keybase: https://keybase.io/eddieantonio

sass:
  style: compressed

plugins:
   - jekyll-redirect-from

whitelist:
    - jekyll-redirect-from
